import { new01, new02, new03 } from "../assets"

export const categories = [
  "News",
  "Articles",
  "Events",
  "Press Realeses",
  "Student Spotlights",
  "Volunteer Spotlights",
  "Partner Spotlights"

]
export const news = [
  {
    image: new01,
    title: "The Title Of The News #01",
    content: '<h2>Title</h2><p>The Rich Text Editor component is a WYSIWYG ("what you see is what you get") editor that provides the best user experience to create and update the content. Users can format their content using standard toolbar commands.</p><p><br></p><blockquote>Quotation: <span style="background-color: rgba(255, 255, 255, 0.1); color: rgb(195, 203, 216); font-family: &quot;Atkinson Hyperlegible&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 16px; text-align: inherit;">There was no possibility of taking a walk that day. We had been wandering, indeed, in the leafless shrubbery an hour in the morning; but since dinner (Mrs. Reed, when there was no company, dined early) the cold winter wind had brought with it clouds so sombre, and a rain so penetrating, that further out-door exercise was now out of the question."</span></blockquote><p><img src="blob:https://ej2.syncfusion.com/983c335b-8f4c-4115-bdfc-e3538719670e" class="e-rte-image e-imginline" alt="logo_icon.png" width="auto" height="auto" style="min-width: 0px; min-height: 0px;"></p><p>subtitle of image</p><p><b>Key features:</b></p><ul><li><p>Provides &lt;IFRAME&gt; and &lt;DIV&gt; modes</p></li><li><p>Capable of handling markdown editing.</p></li><li><p>Contains a modular library to load the necessary functionality on demand.</p></li><li><p>Provides a fully customizable toolbar.</p></li><li><p>Provides HTML view to edit the source directly for developers.</p></li><li><p>Supports third-party library integration.</p></li><li><p>Allows a preview of modified content before saving it.</p></li><li><p>Handles images, hyperlinks, video, hyperlinks, uploads, etc.</p></li><li><p>Contains undo/redo manager.</p></li><li><p>Creates bulleted and numbered lists.</p></li></ul>',
    category: "News",
    createdAt: "2024-02-16T03:45:16.481+00:00",
  },
  {
    image: new02,
    title: "The Title Of The News For MiltiLine News Title #02",
    content: '<h2>Title</h2><p>The Rich Text Editor component is a WYSIWYG ("what you see is what you get") editor that provides the best user experience to create and update the content. Users can format their content using standard toolbar commands.</p><p><br></p><blockquote>Quotation: <span style="background-color: rgba(255, 255, 255, 0.1); color: rgb(195, 203, 216); font-family: &quot;Atkinson Hyperlegible&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 16px; text-align: inherit;">There was no possibility of taking a walk that day. We had been wandering, indeed, in the leafless shrubbery an hour in the morning; but since dinner (Mrs. Reed, when there was no company, dined early) the cold winter wind had brought with it clouds so sombre, and a rain so penetrating, that further out-door exercise was now out of the question."</span></blockquote><p><img src="blob:https://ej2.syncfusion.com/983c335b-8f4c-4115-bdfc-e3538719670e" class="e-rte-image e-imginline" alt="logo_icon.png" width="auto" height="auto" style="min-width: 0px; min-height: 0px;"></p><p>subtitle of image</p><p><b>Key features:</b></p><ul><li><p>Provides &lt;IFRAME&gt; and &lt;DIV&gt; modes</p></li><li><p>Capable of handling markdown editing.</p></li><li><p>Contains a modular library to load the necessary functionality on demand.</p></li><li><p>Provides a fully customizable toolbar.</p></li><li><p>Provides HTML view to edit the source directly for developers.</p></li><li><p>Supports third-party library integration.</p></li><li><p>Allows a preview of modified content before saving it.</p></li><li><p>Handles images, hyperlinks, video, hyperlinks, uploads, etc.</p></li><li><p>Contains undo/redo manager.</p></li><li><p>Creates bulleted and numbered lists.</p></li></ul>',
    category: "News",
    createdAt:"JAN 12, 2024",
  },
  {
    image: new03,
    title: "The Title Of The News #03",
    content: '<h2>Title</h2><p>The Rich Text Editor component is a WYSIWYG ("what you see is what you get") editor that provides the best user experience to create and update the content. Users can format their content using standard toolbar commands.</p><p><br></p><blockquote>Quotation: <span style="background-color: rgba(255, 255, 255, 0.1); color: rgb(195, 203, 216); font-family: &quot;Atkinson Hyperlegible&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 16px; text-align: inherit;">There was no possibility of taking a walk that day. We had been wandering, indeed, in the leafless shrubbery an hour in the morning; but since dinner (Mrs. Reed, when there was no company, dined early) the cold winter wind had brought with it clouds so sombre, and a rain so penetrating, that further out-door exercise was now out of the question."</span></blockquote><p><img src="blob:https://ej2.syncfusion.com/983c335b-8f4c-4115-bdfc-e3538719670e" class="e-rte-image e-imginline" alt="logo_icon.png" width="auto" height="auto" style="min-width: 0px; min-height: 0px;"></p><p>subtitle of image</p><p><b>Key features:</b></p><ul><li><p>Provides &lt;IFRAME&gt; and &lt;DIV&gt; modes</p></li><li><p>Capable of handling markdown editing.</p></li><li><p>Contains a modular library to load the necessary functionality on demand.</p></li><li><p>Provides a fully customizable toolbar.</p></li><li><p>Provides HTML view to edit the source directly for developers.</p></li><li><p>Supports third-party library integration.</p></li><li><p>Allows a preview of modified content before saving it.</p></li><li><p>Handles images, hyperlinks, video, hyperlinks, uploads, etc.</p></li><li><p>Contains undo/redo manager.</p></li><li><p>Creates bulleted and numbered lists.</p></li></ul>',
    category: "Articles",
    createdAt:"JAN 13, 2024",
  },
  {
    image: new03,
    title: "The Title Of The News #03",
    content: '<h2>Title</h2><p>The Rich Text Editor component is a WYSIWYG ("what you see is what you get") editor that provides the best user experience to create and update the content. Users can format their content using standard toolbar commands.</p><p><br></p><blockquote>Quotation: <span style="background-color: rgba(255, 255, 255, 0.1); color: rgb(195, 203, 216); font-family: &quot;Atkinson Hyperlegible&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 16px; text-align: inherit;">There was no possibility of taking a walk that day. We had been wandering, indeed, in the leafless shrubbery an hour in the morning; but since dinner (Mrs. Reed, when there was no company, dined early) the cold winter wind had brought with it clouds so sombre, and a rain so penetrating, that further out-door exercise was now out of the question."</span></blockquote><p><img src="blob:https://ej2.syncfusion.com/983c335b-8f4c-4115-bdfc-e3538719670e" class="e-rte-image e-imginline" alt="logo_icon.png" width="auto" height="auto" style="min-width: 0px; min-height: 0px;"></p><p>subtitle of image</p><p><b>Key features:</b></p><ul><li><p>Provides &lt;IFRAME&gt; and &lt;DIV&gt; modes</p></li><li><p>Capable of handling markdown editing.</p></li><li><p>Contains a modular library to load the necessary functionality on demand.</p></li><li><p>Provides a fully customizable toolbar.</p></li><li><p>Provides HTML view to edit the source directly for developers.</p></li><li><p>Supports third-party library integration.</p></li><li><p>Allows a preview of modified content before saving it.</p></li><li><p>Handles images, hyperlinks, video, hyperlinks, uploads, etc.</p></li><li><p>Contains undo/redo manager.</p></li><li><p>Creates bulleted and numbered lists.</p></li></ul>',
    category: "News",
    createdAt:"JAN 14, 2024",
  },
  {
    image: new02,
    title: "The Title Of The News For MiltiLine News Title #02",
    content: '<h2>Title</h2><p>The Rich Text Editor component is a WYSIWYG ("what you see is what you get") editor that provides the best user experience to create and update the content. Users can format their content using standard toolbar commands.</p><p><br></p><blockquote>Quotation: <span style="background-color: rgba(255, 255, 255, 0.1); color: rgb(195, 203, 216); font-family: &quot;Atkinson Hyperlegible&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 16px; text-align: inherit;">There was no possibility of taking a walk that day. We had been wandering, indeed, in the leafless shrubbery an hour in the morning; but since dinner (Mrs. Reed, when there was no company, dined early) the cold winter wind had brought with it clouds so sombre, and a rain so penetrating, that further out-door exercise was now out of the question."</span></blockquote><p><img src="blob:https://ej2.syncfusion.com/983c335b-8f4c-4115-bdfc-e3538719670e" class="e-rte-image e-imginline" alt="logo_icon.png" width="auto" height="auto" style="min-width: 0px; min-height: 0px;"></p><p>subtitle of image</p><p><b>Key features:</b></p><ul><li><p>Provides &lt;IFRAME&gt; and &lt;DIV&gt; modes</p></li><li><p>Capable of handling markdown editing.</p></li><li><p>Contains a modular library to load the necessary functionality on demand.</p></li><li><p>Provides a fully customizable toolbar.</p></li><li><p>Provides HTML view to edit the source directly for developers.</p></li><li><p>Supports third-party library integration.</p></li><li><p>Allows a preview of modified content before saving it.</p></li><li><p>Handles images, hyperlinks, video, hyperlinks, uploads, etc.</p></li><li><p>Contains undo/redo manager.</p></li><li><p>Creates bulleted and numbered lists.</p></li></ul>',
    category: "News",
    createdAt:"JAN 15, 2024",
  },
  {
    image: new01,
    title: "Nameof Event #01",
    category: "Events",
    content: '<h2>Title</h2><p>The Rich Text Editor component is a WYSIWYG ("what you see is what you get") editor that provides the best user experience to create and update the content. Users can format their content using standard toolbar commands.</p><p><br></p><blockquote>Quotation: <span style="background-color: rgba(255, 255, 255, 0.1); color: rgb(195, 203, 216); font-family: &quot;Atkinson Hyperlegible&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 16px; text-align: inherit;">There was no possibility of taking a walk that day. We had been wandering, indeed, in the leafless shrubbery an hour in the morning; but since dinner (Mrs. Reed, when there was no company, dined early) the cold winter wind had brought with it clouds so sombre, and a rain so penetrating, that further out-door exercise was now out of the question."</span></blockquote><p><img src="blob:https://ej2.syncfusion.com/983c335b-8f4c-4115-bdfc-e3538719670e" class="e-rte-image e-imginline" alt="logo_icon.png" width="auto" height="auto" style="min-width: 0px; min-height: 0px;"></p><p>subtitle of image</p><p><b>Key features:</b></p><ul><li><p>Provides &lt;IFRAME&gt; and &lt;DIV&gt; modes</p></li><li><p>Capable of handling markdown editing.</p></li><li><p>Contains a modular library to load the necessary functionality on demand.</p></li><li><p>Provides a fully customizable toolbar.</p></li><li><p>Provides HTML view to edit the source directly for developers.</p></li><li><p>Supports third-party library integration.</p></li><li><p>Allows a preview of modified content before saving it.</p></li><li><p>Handles images, hyperlinks, video, hyperlinks, uploads, etc.</p></li><li><p>Contains undo/redo manager.</p></li><li><p>Creates bulleted and numbered lists.</p></li></ul>',
    createdAt:"JAN 16, 2024",
    eventDate: "2024-04-26T03:45:16.481+00:00"
  },
  {
    image: new01,
    title: "Nameof Event #02",
    category: "Events",
    content: '<h2>Title</h2><p>The Rich Text Editor component is a WYSIWYG ("what you see is what you get") editor that provides the best user experience to create and update the content. Users can format their content using standard toolbar commands.</p><p><br></p><blockquote>Quotation: <span style="background-color: rgba(255, 255, 255, 0.1); color: rgb(195, 203, 216); font-family: &quot;Atkinson Hyperlegible&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 16px; text-align: inherit;">There was no possibility of taking a walk that day. We had been wandering, indeed, in the leafless shrubbery an hour in the morning; but since dinner (Mrs. Reed, when there was no company, dined early) the cold winter wind had brought with it clouds so sombre, and a rain so penetrating, that further out-door exercise was now out of the question."</span></blockquote><p><img src="blob:https://ej2.syncfusion.com/983c335b-8f4c-4115-bdfc-e3538719670e" class="e-rte-image e-imginline" alt="logo_icon.png" width="auto" height="auto" style="min-width: 0px; min-height: 0px;"></p><p>subtitle of image</p><p><b>Key features:</b></p><ul><li><p>Provides &lt;IFRAME&gt; and &lt;DIV&gt; modes</p></li><li><p>Capable of handling markdown editing.</p></li><li><p>Contains a modular library to load the necessary functionality on demand.</p></li><li><p>Provides a fully customizable toolbar.</p></li><li><p>Provides HTML view to edit the source directly for developers.</p></li><li><p>Supports third-party library integration.</p></li><li><p>Allows a preview of modified content before saving it.</p></li><li><p>Handles images, hyperlinks, video, hyperlinks, uploads, etc.</p></li><li><p>Contains undo/redo manager.</p></li><li><p>Creates bulleted and numbered lists.</p></li></ul>',
    createdAt:"JAN 18, 2024",
    eventDate: "2024-04-26T03:45:16.481+00:00"
  },
  {
    image: new01,
    title: "Nameof Event #03",
    category: "Events",
    content: '<h2>Title</h2><p>The Rich Text Editor component is a WYSIWYG ("what you see is what you get") editor that provides the best user experience to create and update the content. Users can format their content using standard toolbar commands.</p><p><br></p><blockquote>Quotation: <span style="background-color: rgba(255, 255, 255, 0.1); color: rgb(195, 203, 216); font-family: &quot;Atkinson Hyperlegible&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 16px; text-align: inherit;">There was no possibility of taking a walk that day. We had been wandering, indeed, in the leafless shrubbery an hour in the morning; but since dinner (Mrs. Reed, when there was no company, dined early) the cold winter wind had brought with it clouds so sombre, and a rain so penetrating, that further out-door exercise was now out of the question."</span></blockquote><p><img src="blob:https://ej2.syncfusion.com/983c335b-8f4c-4115-bdfc-e3538719670e" class="e-rte-image e-imginline" alt="logo_icon.png" width="auto" height="auto" style="min-width: 0px; min-height: 0px;"></p><p>subtitle of image</p><p><b>Key features:</b></p><ul><li><p>Provides &lt;IFRAME&gt; and &lt;DIV&gt; modes</p></li><li><p>Capable of handling markdown editing.</p></li><li><p>Contains a modular library to load the necessary functionality on demand.</p></li><li><p>Provides a fully customizable toolbar.</p></li><li><p>Provides HTML view to edit the source directly for developers.</p></li><li><p>Supports third-party library integration.</p></li><li><p>Allows a preview of modified content before saving it.</p></li><li><p>Handles images, hyperlinks, video, hyperlinks, uploads, etc.</p></li><li><p>Contains undo/redo manager.</p></li><li><p>Creates bulleted and numbered lists.</p></li></ul>',
    createdAt:"JAN 19, 2024",
    eventDate: "2024-04-26T03:45:16.481+00:00"
  },
]
